# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40faddc1f78735e09dc7e4a58a5610d65c2cd7256057150294f61e503628610314ccd176328f6492ef3360488786aee91a5f8afdcd92e54f65426077c8b219db

test:
  secret_key_base: 609a3a698fdce23afd6cccd5bc0eef0fa30ada047a40a232e986b274134ee3dadccfd03a348890dae38f5c4fe758319d252044b6ace2c2505de223344d952f0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
